labels: /local_raid1/sgoetz/STORE/CONFIG/CT_CLASSIFER3/labels.tsv
test_size: 0.2
seed: 87
params:
  boosting: gbdt
  objective: binary
  metric:
    - binary_logloss
    - auc
  tree_learner: serial
  data_sample_strategy: bagging
  learning_rate: 0.03
  num_leaves: 80
  max_depth: 8
  min_data_in_leaf: 300
  min_sum_hessian_in_leaf: 2
  bagging_fraction: 0.7
  bagging_freq: 1
  feature_fraction: 0.8
  feature_fraction_bynode: 0.8
  lambda_l1: 0.5
  lambda_l2: 5
  min_gain_to_split: 0.01
  drop_rate: 0.1
  max_drop: 50
  skip_drop: 0.5
  top_rate: 0.2
  other_rate: 0.1
  min_data_per_group: 100
  max_cat_threshold: 32
  cat_l2: 10
  cat_smooth: 10
  max_cat_to_onehot: 4
  top_k: 20
  monotone_constraints_method: basic
  refit_decay_rate: 0.9
  verbosity: -1
  max_bin: 255
  min_data_in_bin: 3
  bin_construct_sample_cnt: 200000
  alpha: 0.9
  poisson_max_delta_step: 0.7
  tweedie_variance_power: 1.5