labels: /local_raid1/sgoetz/STORE/CONFIG/CTC/JACKIE_MATCHED_TRIALS.tsv
test_size: 0.2
seed: 36
params:
  boosting: gbdt
  objective: binary
  metric:
    - binary_logloss
    - auc
    # - average_precision
  first_metric_only: true
  feature_pre_filter: false
  learning_rate: 0.05
  num_leaves: 80
  max_bin: 255
  verbosity: -1