labels: /local_raid1/sgoetz/STORE/CONFIG/CTC/JACKIE_MATCHED_TRIALS.tsv
test_size: 0.2
seed: 75
params:
  boosting: gbdt
  objective: binary
  metric:
    - auc
    # - average_precision
    # - binary_logloss
  first_metric_only: true
  learning_rate: 0.01
  num_leaves: 31
  max_depth: 12
  bagging_fraction: 0.8
  feature_fraction: 0.2
  feature_fraction_bynode: 0.5
  min_data_in_leaf: 200
  bagging_freq: 1
  lambda_l2: 5.0
  max_bin: 15
  verbosity: -1