labels: /local_raid1/sgoetz/STORE/CONFIG/CT_CLASSIFER3/labels.tsv
test_size: 0.2
seed: 87
params:
  boosting: gbdt
  objective: binary
  metric:
    - binary_logloss
    - auc
  learning_rate: 1e-3
  num_leaves: 64
  max_depth: -1
  min_data_in_leaf: 20
  bagging_fraction: 0.8
  bagging_freq: 1
  feature_fraction: 0.9
  lambda_l1: 0.0
  lambda_l2: 0.0
  max_bin: 15
  verbosity: -1