labels: /local_raid1/sgoetz/STORE/CONFIG/CT_CLASSIFER3/labels0.tsv
test_size: 0.3
seed: 25
params:
  boosting: gbdt
  objective: binary
  metric:
    - average_precision
    - auc
    # - binary_logloss
    # - accuracy
  first_metric_only: true
  feature_pre_filter: false
  learning_rate: 0.03
  num_leaves: 7
  lambda_l1: 1.0
  lambda_l2: 5.0
  max_bin: 255
  verbosity: -1